name: voicegpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_chat_ui: ^1.6.6
  flutter_chat_ui:
    git:
      url: https://github.com/flyerhq/flutter_chat_ui.git
      ref: main 
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  http: ^0.13.5
  mobx: ^2.1.4
  sembast: ^3.4.3+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/gpt-logo.png"